
$disable_unattended_upgrades =<<-SCRIPT
echo "-- Disabling unattended upgrades --"
cat << EOF > /etc/apt/apt.conf.d/51disable-unattended-upgrades
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "0";
EOF
SCRIPT

$setup_quarifier_environment =<<-SCRIPT
set -e
echo "-- ISUCON9 quarifier setup --"
export DEBIAN_FRONTEND="noninteractive"
apt update
apt -y install python-pip
pip install ansible==2.8.3
SCRIPT

$ansible_provision_web =<<-SCRIPT
set -e
cd /tmp/isucon9-qualify/provisioning
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -vvv webapp.yml
SCRIPT

$ansible_provision_bench =<<-SCRIPT
set -e
cd /tmp/isucon9-qualify/provisioning
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -vvv bench.yml
SCRIPT


Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"
  3.times do |num|
    config.vm.define "image-#{num}" do |web|
      web.vm.network "private_network", ip: "192.168.33.#{10+num}"
      web.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = 4096
      end
      web.vm.provision :shell, inline: $disable_unattended_upgrades
      web.vm.provision :shell, inline: $setup_quarifier_environment
      web.vm.provision "file", source: "..", destination: "/tmp/isucon9-qualify"
      web.vm.provision :shell, inline: $ansible_provision_web
      web.vm.provision :shell, inline: "rm -rf /tmp/isucon9-qualify"
    end
  end

  config.vm.define "bench" do |bench|
    bench.vm.network "private_network", ip:"192.168.33.9"

    bench.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 4096
    end
    bench.vm.provision :shell, inline: $disable_unattended_upgrades
    bench.vm.provision :shell, inline: $setup_quarifier_environment
    bench.vm.provision "file", source: "..", destination: "/tmp/isucon9-qualify"
    bench.vm.provision :shell, inline: $ansible_provision_bench
    bench.vm.provision :shell, inline: "rm -rf /tmp/isucon9-qualify"
  end
end
